### PR TITLE
Upgrade to Terraform 0.12

### PR DESCRIPTION
**Pull request by damacus**
All files in the global folder have been upgraded to use the newer Terraform 0.12 syntax.

The upgrade was performed using the `terraform 0.12upgrade` command and manual approval. 

There are some minor changes in the lambdas where the source code hashes
have changed. This is expected withthe current implmenetation of the
modules.

See below for the plan. 

<details><summary>terraform plan</summary>
<p>

```shell
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place
-/+ destroy and then create replacement
 <= read (data resources)

Terraform will perform the following actions:

  # module.aws_account_logging.data.archive_file.cloudtrail_zip will be read during apply
  # (config refers to values not yet known)
 <= data "archive_file" "cloudtrail_zip"  {
      + id                  = (known after apply)
      + output_base64sha256 = (known after apply)
      + output_md5          = (known after apply)
      + output_path         = "/tmp/cloudtrail.zip"
      + output_sha          = (known after apply)
      + output_size         = (known after apply)
      + source_dir          = "modules/aws_account_logging/cloudtrail"
      + type                = "zip"
    }

  # module.aws_account_logging.data.archive_file.s3logs_zip will be read during apply
  # (config refers to values not yet known)
 <= data "archive_file" "s3logs_zip"  {
      + id                  = (known after apply)
      + output_base64sha256 = (known after apply)
      + output_md5          = (known after apply)
      + output_path         = "/tmp/s3logs.zip"
      + output_sha          = (known after apply)
      + output_size         = (known after apply)
      + source_dir          = "modules/aws_account_logging/s3logs"
      + type                = "zip"
    }

  # module.aws_account_logging.aws_lambda_function.cloudtrail_to_elasticsearch will be updated in-place
  ~ resource "aws_lambda_function" "cloudtrail_to_elasticsearch" {
        arn                            = "arn:aws:lambda:eu-west-1:593291632749:function:cloudtrail_to_elasticsearch"
        description                    = "Ships Cloudtrail logs to Elasticsearch"
        filename                       = "/tmp/cloudtrail.zip"
        function_name                  = "cloudtrail_to_elasticsearch"
        handler                        = "cloudtrail_to_es.lambda_handler"
        id                             = "cloudtrail_to_elasticsearch"
        invoke_arn                     = "arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:593291632749:function:cloudtrail_to_elasticsearch/invocations"
      ~ last_modified                  = "2020-09-08T13:51:54.469+0000" -> (known after apply)
        layers                         = []
        memory_size                    = 128
        publish                        = false
        qualified_arn                  = "arn:aws:lambda:eu-west-1:593291632749:function:cloudtrail_to_elasticsearch:$LATEST"
        reserved_concurrent_executions = -1
        role                           = "arn:aws:iam::593291632749:role/cloudtrail_to_elasticsearch"
        runtime                        = "python3.6"
      ~ source_code_hash               = "zSCvWcHCFYYv5fw3Oed5Vk01Psz36Vds36m28N9MKwc=" -> (known after apply)
        source_code_size               = 596295
        tags                           = {}
        timeout                        = 30
        version                        = "$LATEST"

        environment {
            variables = {
                "ES_DOMAIN"   = "f58ddb963b371b72f957e6cd3660f350.eu-west-1.aws.found.io"
                "ES_PASSWORD" = "kAPD4zwPb38aUTdjOqiyEZAE"
                "ES_PORT"     = "9243"
                "ES_SCHEME"   = "https"
                "ES_USERNAME" = "elastic"
            }
        }

        timeouts {}

        tracing_config {
            mode = "PassThrough"
        }
    }

  # module.aws_account_logging.aws_lambda_function.s3_logs_to_elasticsearch will be updated in-place
  ~ resource "aws_lambda_function" "s3_logs_to_elasticsearch" {
        arn                            = "arn:aws:lambda:eu-west-1:593291632749:function:s3_logs_to_elasticsearch"
        description                    = "Ships s3 access logs to Elasticsearch"
        filename                       = "/tmp/s3logs.zip"
        function_name                  = "s3_logs_to_elasticsearch"
        handler                        = "s3_to_es.lambda_handler"
        id                             = "s3_logs_to_elasticsearch"
        invoke_arn                     = "arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:593291632749:function:s3_logs_to_elasticsearch/invocations"
      ~ last_modified                  = "2020-09-08T13:55:32.631+0000" -> (known after apply)
        layers                         = []
        memory_size                    = 128
        publish                        = false
        qualified_arn                  = "arn:aws:lambda:eu-west-1:593291632749:function:s3_logs_to_elasticsearch:$LATEST"
        reserved_concurrent_executions = -1
        role                           = "arn:aws:iam::593291632749:role/s3_logs_to_elasticsearch"
        runtime                        = "python3.6"
      ~ source_code_hash               = "iTQa7uf8NF1ysujn+YOCU+IyKsZmoOepYmdHNF82lMs=" -> (known after apply)
        source_code_size               = 1015795
        tags                           = {}
        timeout                        = 5
        version                        = "$LATEST"

        environment {
            variables = {
                "ES_DOMAIN"   = "f58ddb963b371b72f957e6cd3660f350.eu-west-1.aws.found.io"
                "ES_PASSWORD" = "kAPD4zwPb38aUTdjOqiyEZAE"
                "ES_PORT"     = "9243"
                "ES_SCHEME"   = "https"
                "ES_USERNAME" = "elastic"
            }
        }

        timeouts {}

        tracing_config {
            mode = "PassThrough"
        }
    }

  # module.aws_account_logging.aws_lambda_function.vpcflowlogs_to_elasticsearch will be updated in-place
  ~ resource "aws_lambda_function" "vpcflowlogs_to_elasticsearch" {
        arn                            = "arn:aws:lambda:eu-west-1:593291632749:function:vpcflowlogs_to_elasticsearch"
        filename                       = "/tmp/vpcflowlogs.zip"
        function_name                  = "vpcflowlogs_to_elasticsearch"
        handler                        = "vpcflowlogs_to_elasticsearch.lambda_handler"
        id                             = "vpcflowlogs_to_elasticsearch"
        invoke_arn                     = "arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:593291632749:function:vpcflowlogs_to_elasticsearch/invocations"
      ~ last_modified                  = "2020-09-08T13:55:30.958+0000" -> (known after apply)
        layers                         = []
        memory_size                    = 128
        publish                        = false
        qualified_arn                  = "arn:aws:lambda:eu-west-1:593291632749:function:vpcflowlogs_to_elasticsearch:$LATEST"
        reserved_concurrent_executions = -1
        role                           = "arn:aws:iam::593291632749:role/vpcflowlogs_to_elasticsearch"
        runtime                        = "python3.6"
      ~ source_code_hash               = "oacwk6lCkSJ9JTM1L6Uiu0ugLMaUxew3Zzh+f3WJOKE=" -> "JPW77K8kAi+DBKbOO0dWFM170fGUMEOdJjrEKbzilBY="
        source_code_size               = 9778354
        tags                           = {}
        timeout                        = 30
        version                        = "$LATEST"

        environment {
            variables = {
                "ES_DOMAIN"   = "f58ddb963b371b72f957e6cd3660f350.eu-west-1.aws.found.io"
                "ES_PASSWORD" = "kAPD4zwPb38aUTdjOqiyEZAE"
                "ES_PORT"     = "9243"
                "ES_SCHEME"   = "https"
                "ES_USERNAME" = "elastic"
            }
        }

        timeouts {}

        tracing_config {
            mode = "PassThrough"
        }
    }

  # module.aws_account_logging.null_resource.cloudtrail_install_deps must be replaced
-/+ resource "null_resource" "cloudtrail_install_deps" {
      ~ id       = "6534559863060079763" -> (known after apply)
      + triggers = (known after apply) # forces replacement
    }

  # module.aws_account_logging.null_resource.s3logs_install_deps must be replaced
-/+ resource "null_resource" "s3logs_install_deps" {
      ~ id       = "8225546461971726865" -> (known after apply)
      + triggers = (known after apply) # forces replacement
    }

  # module.aws_account_logging.null_resource.vpcflowlogs_install_deps must be replaced
-/+ resource "null_resource" "vpcflowlogs_install_deps" {
      ~ id       = "6845164438476661208" -> (known after apply)
      + triggers = (known after apply) # forces replacement
    }

  # module.kubernetes_etcd_ebs_snapshot.aws_lambda_function.lambda_function[0] will be updated in-place
  ~ resource "aws_lambda_function" "lambda_function" {
        arn                            = "arn:aws:lambda:eu-west-1:593291632749:function:create_etcd_ebs_snapshot"
        filename                       = "assets/create_etcd_ebs_snapshot/create_etcd_ebs_snapshot.zip"
        function_name                  = "create_etcd_ebs_snapshot"
        handler                        = "create_etcd_ebs_snapshot"
        id                             = "create_etcd_ebs_snapshot"
        invoke_arn                     = "arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:593291632749:function:create_etcd_ebs_snapshot/invocations"
      ~ last_modified                  = "2019-06-07T09:14:52.847+0000" -> (known after apply)
        layers                         = []
        memory_size                    = 128
        publish                        = false
        qualified_arn                  = "arn:aws:lambda:eu-west-1:593291632749:function:create_etcd_ebs_snapshot:$LATEST"
        reserved_concurrent_executions = -1
        role                           = "arn:aws:iam::593291632749:role/create_etcd_ebs_snapshot"
        runtime                        = "go1.x"
      ~ source_code_hash               = "/sPD7hXrgqGRhFpxPWK88iSspbohU+5Do8NlPC8KJa4=" -> "g6kErAbI0iZkvnKM5oYlzA/kVF81lCCeMM37QNJSy30="
        source_code_size               = 3967484
        tags                           = {}
        timeout                        = 3
        version                        = "$LATEST"

        environment {
            variables = {
                "INSTANCE_TAG_KEY"   = "k8s.io/role/master"
                "INSTANCE_TAG_VALUE" = "1"
                "TAG_KEY"            = "etcd"
                "TAG_VALUE"          = "1"
            }
        }

        timeouts {}

        tracing_config {
            mode = "PassThrough"
        }
    }

  # module.kubernetes_prune_ebs_snapshots.aws_lambda_function.lambda_function[0] will be updated in-place
  ~ resource "aws_lambda_function" "lambda_function" {
        arn                            = "arn:aws:lambda:eu-west-1:593291632749:function:prune_ebs_snapshots"
        filename                       = "assets/prune_ebs_snapshots/prune_ebs_snapshots.zip"
        function_name                  = "prune_ebs_snapshots"
        handler                        = "prune_ebs_snapshots"
        id                             = "prune_ebs_snapshots"
        invoke_arn                     = "arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:593291632749:function:prune_ebs_snapshots/invocations"
      ~ last_modified                  = "2019-06-07T10:28:38.990+0000" -> (known after apply)
        layers                         = []
        memory_size                    = 128
        publish                        = false
        qualified_arn                  = "arn:aws:lambda:eu-west-1:593291632749:function:prune_ebs_snapshots:$LATEST"
        reserved_concurrent_executions = -1
        role                           = "arn:aws:iam::593291632749:role/prune_ebs_snapshots"
        runtime                        = "go1.x"
      ~ source_code_hash               = "XbciQ2gv0B2pGxu1t4iwRbyHjemfzQRmCBlXm/Xz+8w=" -> "+/ZBrgVRhLB0Rvm4sPadI/70nFNb/fs8tVdKAZABDfM="
        source_code_size               = 3942739
        tags                           = {}
        timeout                        = 3
        version                        = "$LATEST"

        environment {
            variables = {
                "DAYS_OLD"           = "14"
                "SNAPSHOT_TAG_KEY"   = "etcd"
                "SNAPSHOT_TAG_VALUE" = "1"
            }
        }

        timeouts {}

        tracing_config {
            mode = "PassThrough"
        }
    }

Plan: 3 to add, 5 to change, 3 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.

```
<p/>
</details>

### CODE REVIEW

**Comment by damacus** [comment]
I'm expecting CircleCI to fail validation here as it's checking using an old version, with and old syntax of the validate command. 

Happy to also add GitHub check in for validation here.
I'm preposing to switch to GitHub checks as we:

- can trigger on a per folder basis
- are moving to GitHub Actions long term

**Comment by tomskelley-gjs** [comment]
So looks like you're updating 5 lambdas presumably the md5sums have changed there. Are the delete/creates the null resources to install all the dependencies for the lambdas? Have these just changed because the lambdas are changing? Presumably the content is the same?

**Comment by damacus** [comment]
They're being triggered right now because they're based on a timestamp, so it'll always trigger 😢

**Review by tomskelley-gjs — APPROVED** [review]
OK in that case LGTM 👍

**Pull request merged**
