### PR TITLE
Remove the EBS snapshot & pruning modules

### PR DESCRIPTION
**Pull request by damacus**
Neither of these modules work correctly.

Pruning has never worked
Snapshot creation constantly errors on "some" volumes as we are creating
them too fast. We will replace these modules with a different approach.

### CODE REVIEW

**Comment by andylightfoot** [comment]
I've had a quick look and it looks like the EBS Snapshot Lambda is successfully creating some snapshots of the etcd volumes currently.  So I think it would be better to implement the replacement first before deleting what we have already.

**Comment by damacus** [comment]
Converting to a draft whilst we come up with a plan for a replacement 👍

**Comment by andylightfoot** [comment]
> Converting to a draft whilst we come up with a plan for a replacement 👍

Sounds good

**Comment by damacus** [comment]
Looks like this module of @xoen's is actually what we want long term. 

https://github.com/ministryofjustice/analytics-platform-ops/pull/301

**Pull request closed without merging**
