### PR TITLE
Changing yml to reflect actual k8s version on alpha

### PR DESCRIPTION
**Pull request by davidread**
We're running kubernetes 1.10.5 on alpha, as seen:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-28T15:20:58Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

Dev's cluster.yml got update on the recent upgrade, but this one was missed, it seems.

### CODE REVIEW

**Comment by xoen** [comment]
Looks good to me (but I don't know if @kerin didn't do this before for some reason).

Speaking of, shouldn't the kops channel change from `alpha` to `stable` as well as done [here](https://github.com/ministryofjustice/analytics-platform-ops/commit/3312cf6781bb31600595251d93e4b50773452a61)?

**Comment by kerin** [comment]
Yep, looks like I missed the alpha cluster YAML - that should be using the `stable` channel now as well.

We should also look at using [kops templating](https://github.com/kubernetes/kops/blob/master/docs/cluster_template.md) at some point, so that we don't need to maintain a clusterspec YAML file per environment.

**Comment by davidread** [comment]
Good spot, I've changed the channel to stable too.

@xoen ready for re-review

Nice idea on the kops templates - that sounds easier for automatically filling in the values too, compared to dozens of yq calls.

**Comment by xoen** [comment]
@davidread looking good 👍

**Pull request merged**
