### PR TITLE
Upgrade k8s 1.11

### PR DESCRIPTION
**Pull request by djsd123**
[Trello](https://trello.com/c/xyPlXi13)
See [KOPs Release notes](https://github.com/kubernetes/kops/blob/master/docs/releases/1.11NOTES.md)
    
Quarterly KOPS release -> Quarterly Cluster upgrade
    
Somewhat significant to our cluster.  Kops deploys cluster which
addresses this [vulnerability](https://medium.com/handy-tech/analysis-of-a-kubernetes-hack-backdooring-through-kubelet-823be5c3d67c) by default.

### CODE REVIEW

**Comment by xoen** [comment]
Starting to have a look. Question: How does this affect us?

> kops will attempt to remove NLBs (also known as ELB v2) that are tagged as created by the cluster. Please double-check the preview from kops delete cluster before allowing deletion.

On top of my head, we have mixture of Classic, Application and NLB load balancers. Some of them created by ingress controller. Not sure if above matters and what would be the impact to be honest.

**Comment by djsd123** [comment]
@xoen, thanks 🙏  
Yes, I also wondered about that.  It does not apply to our NLBs but I thought it was an undesirable consequence in any case. I gave up looking to see why.

P.S.  deployed in dev

**Comment by xoen** [comment]
Maybe I don't understand what they mean by "created by the cluster", aren't our NLBs for the cluster ingress created "by the cluster"? Anyway, good to watch out for possible problems but if you didn't see anything weird `dev` is probably OK.

**Comment by djsd123** [comment]
Oh, snap.  Thanks, @davidread.

**Pull request merged**
